# Generated by Django 4.2.1 on 2023-05-28 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Details',
            fields=[
                ('emp_name', models.CharField(max_length=100)),
                ('emp_reg_no', models.IntegerField(primary_key=True, serialize=False)),
                ('shift_choice', models.CharField(choices=[('1', 'Morning'), ('2', 'Night')], max_length=1)),
            ],
        ),
    ]
