# Generated by Django 4.2.1 on 2023-05-28 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empdata', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='details',
            name='password',
            field=models.CharField(default='password', max_length=50),
        ),
    ]
