# Generated by Django 4.2.1 on 2023-05-28 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empdata', '0002_details_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='shift_choice',
            field=models.CharField(choices=[('Morning', 'Morning'), ('Morning', 'Night')], max_length=10),
        ),
    ]
